# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us21.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(560, 2, 221, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_12.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.w_title = QtWidgets.QLineEdit(self.centralwidget)
        self.w_title.setGeometry(QtCore.QRect(280, 25, 281, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_title.setFont(font)
        self.w_title.setText("")
        self.w_title.setObjectName("w_title")
        self.w_counts = QtWidgets.QLineEdit(self.centralwidget)
        self.w_counts.setGeometry(QtCore.QRect(780, 25, 91, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_counts.setFont(font)
        self.w_counts.setObjectName("w_counts")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 2, 281, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_6.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 2, 271, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_5.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 2, 91, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_7.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.f_title = QtWidgets.QLineEdit(self.centralwidget)
        self.f_title.setGeometry(QtCore.QRect(280, 50, 281, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.f_title.setFont(font)
        self.f_title.setText("")
        self.f_title.setObjectName("f_title")
        self.w_custom_index = QtWidgets.QLineEdit(self.centralwidget)
        self.w_custom_index.setGeometry(QtCore.QRect(10, 25, 271, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_custom_index.setFont(font)
        self.w_custom_index.setText("")
        self.w_custom_index.setObjectName("w_custom_index")
        self.f_custom_index = QtWidgets.QLineEdit(self.centralwidget)
        self.f_custom_index.setGeometry(QtCore.QRect(10, 50, 271, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.f_custom_index.setFont(font)
        self.f_custom_index.setText("")
        self.f_custom_index.setObjectName("f_custom_index")
        self.treeView = QtWidgets.QTableWidget(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 80, 561, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.treeView.setFont(font)
        self.treeView.setStyleSheet("QTableWidget {\n"
"    alternate-background-color: #f2f2f2; /* 隔行背景顏色 */\n"
"    selection-background-color: #0078d7;  /* 選擇背景顏色 */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表頭背景顏色 */\n"
"}")
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setColumnCount(0)
        self.treeView.setObjectName("treeView")
        self.treeView.setRowCount(0)
        self.treeView.verticalHeader().setDefaultSectionSize(24)
        self.w_content = QtWidgets.QLineEdit(self.centralwidget)
        self.w_content.setGeometry(QtCore.QRect(560, 25, 221, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_content.setFont(font)
        self.w_content.setText("")
        self.w_content.setObjectName("w_content")
        self.f_content = QtWidgets.QLineEdit(self.centralwidget)
        self.f_content.setGeometry(QtCore.QRect(560, 50, 221, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.f_content.setFont(font)
        self.f_content.setText("")
        self.f_content.setObjectName("f_content")
        self.query = QtWidgets.QPushButton(self.centralwidget)
        self.query.setGeometry(QtCore.QRect(880, 0, 131, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.query.setFont(font)
        self.query.setFocusPolicy(QtCore.Qt.NoFocus)
        self.query.setToolTip("")
        self.query.setObjectName("query")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.w_custom_index, self.w_title)
        MainWindow.setTabOrder(self.w_title, self.w_content)
        MainWindow.setTabOrder(self.w_content, self.w_counts)
        MainWindow.setTabOrder(self.w_counts, self.f_custom_index)
        MainWindow.setTabOrder(self.f_custom_index, self.f_title)
        MainWindow.setTabOrder(self.f_title, self.f_content)
        MainWindow.setTabOrder(self.f_content, self.treeView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "檔案類型"))
        self.w_counts.setText(_translate("MainWindow", "200"))
        self.label_6.setText(_translate("MainWindow", "摘要"))
        self.label_5.setText(_translate("MainWindow", "顯示標題"))
        self.label_7.setText(_translate("MainWindow", "限制筆數"))
        self.query.setText(_translate("MainWindow", "查詢"))
