# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us15.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTableWidget(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 60, 551, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.treeView.setFont(font)
        self.treeView.setStyleSheet("QTableWidget {\n"
"    alternate-background-color: #f2f2f2; /* 隔行背景顏色 */\n"
"    selection-background-color: #0078d7;  /* 選擇背景顏色 */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表頭背景顏色 */\n"
"}")
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setColumnCount(0)
        self.treeView.setObjectName("treeView")
        self.treeView.setRowCount(0)
        self.treeView.verticalHeader().setDefaultSectionSize(24)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(575, 60, 261, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.w_content_type = QtWidgets.QComboBox(self.centralwidget)
        self.w_content_type.setGeometry(QtCore.QRect(430, 33, 221, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_content_type.setFont(font)
        self.w_content_type.setStyleSheet("")
        self.w_content_type.setObjectName("w_content_type")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 211, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_5.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.w_counts = QtWidgets.QLineEdit(self.centralwidget)
        self.w_counts.setGeometry(QtCore.QRect(650, 33, 81, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_counts.setFont(font)
        self.w_counts.setObjectName("w_counts")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 10, 221, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_12.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.w_title = QtWidgets.QLineEdit(self.centralwidget)
        self.w_title.setGeometry(QtCore.QRect(10, 33, 211, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_title.setFont(font)
        self.w_title.setText("")
        self.w_title.setObjectName("w_title")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 10, 81, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_7.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.w_summary = QtWidgets.QLineEdit(self.centralwidget)
        self.w_summary.setGeometry(QtCore.QRect(220, 33, 211, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.w_summary.setFont(font)
        self.w_summary.setText("")
        self.w_summary.setObjectName("w_summary")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 10, 211, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_6.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.query = QtWidgets.QPushButton(self.centralwidget)
        self.query.setGeometry(QtCore.QRect(740, 10, 101, 48))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.query.setFont(font)
        self.query.setFocusPolicy(QtCore.Qt.NoFocus)
        self.query.setToolTip("")
        self.query.setObjectName("query")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.w_title, self.w_summary)
        MainWindow.setTabOrder(self.w_summary, self.w_content_type)
        MainWindow.setTabOrder(self.w_content_type, self.w_counts)
        MainWindow.setTabOrder(self.w_counts, self.treeView)
        MainWindow.setTabOrder(self.treeView, self.scrollArea)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "顯示標題"))
        self.w_counts.setText(_translate("MainWindow", "200"))
        self.label_12.setText(_translate("MainWindow", "檔案類型"))
        self.label_7.setText(_translate("MainWindow", "限制筆數"))
        self.label_6.setText(_translate("MainWindow", "摘要"))
        self.query.setText(_translate("MainWindow", "查詢"))
