# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us05.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 244)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(150, 20, 381, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setText("")
        self.email.setObjectName("email")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 101, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_2.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(150, 60, 381, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 101, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_4.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 101, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_5.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.full_name = QtWidgets.QLineEdit(self.centralwidget)
        self.full_name.setGeometry(QtCore.QRect(150, 100, 381, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.full_name.setFont(font)
        self.full_name.setText("")
        self.full_name.setObjectName("full_name")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(200, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.login.setFont(font)
        self.login.setObjectName("login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.email, self.password)
        MainWindow.setTabOrder(self.password, self.full_name)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.label_5.setText(_translate("MainWindow", "Username:"))
        self.login.setText(_translate("MainWindow", "Login"))
