# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 0, 561, 401))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.treeView.setFont(font)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.pd_edit = QtWidgets.QPushButton(self.centralwidget)
        self.pd_edit.setEnabled(False)
        self.pd_edit.setGeometry(QtCore.QRect(590, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.pd_edit.setFont(font)
        self.pd_edit.setObjectName("pd_edit")
        self.pd_check = QtWidgets.QPushButton(self.centralwidget)
        self.pd_check.setEnabled(False)
        self.pd_check.setGeometry(QtCore.QRect(590, 90, 101, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.pd_check.setFont(font)
        self.pd_check.setObjectName("pd_check")
        self.pd_upload = QtWidgets.QPushButton(self.centralwidget)
        self.pd_upload.setEnabled(False)
        self.pd_upload.setGeometry(QtCore.QRect(590, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.pd_upload.setFont(font)
        self.pd_upload.setObjectName("pd_upload")
        self.pd_release = QtWidgets.QPushButton(self.centralwidget)
        self.pd_release.setEnabled(False)
        self.pd_release.setGeometry(QtCore.QRect(590, 230, 101, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.pd_release.setFont(font)
        self.pd_release.setObjectName("pd_release")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pd_edit.setToolTip(_translate("MainWindow", "以編輯器開啟"))
        self.pd_edit.setText(_translate("MainWindow", "編輯"))
        self.pd_check.setToolTip(_translate("MainWindow", "檢查資料"))
        self.pd_check.setText(_translate("MainWindow", "檢查"))
        self.pd_upload.setToolTip(_translate("MainWindow", "上傳預覽版"))
        self.pd_upload.setText(_translate("MainWindow", "上傳"))
        self.pd_release.setToolTip(_translate("MainWindow", "正式發佈"))
        self.pd_release.setText(_translate("MainWindow", "發佈"))
