# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us09.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 285)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editor = QtWidgets.QLineEdit(self.centralwidget)
        self.editor.setGeometry(QtCore.QRect(170, 60, 621, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.editor.setFont(font)
        self.editor.setText("")
        self.editor.setObjectName("editor")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 131, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_2.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(340, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.browse_editor = QtWidgets.QPushButton(self.centralwidget)
        self.browse_editor.setGeometry(QtCore.QRect(690, 90, 101, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.browse_editor.setFont(font)
        self.browse_editor.setObjectName("browse_editor")
        self.show_cmd_window = QtWidgets.QCheckBox(self.centralwidget)
        self.show_cmd_window.setGeometry(QtCore.QRect(180, 123, 171, 19))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.show_cmd_window.setFont(font)
        self.show_cmd_window.setObjectName("show_cmd_window")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 180, 831, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 131, 24))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_3.setStyleSheet("QLabel {\n"
"    border: 1px solid black; /* 邊框粗細與顏色 */\n"
"    padding: 2px;           /* 內邊距 */\n"
"}")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "編輯器路徑:"))
        self.save.setText(_translate("MainWindow", "儲存"))
        self.browse_editor.setText(_translate("MainWindow", "瀏覽..."))
        self.show_cmd_window.setText(_translate("MainWindow", "顯示"))
        self.label_3.setText(_translate("MainWindow", "偵錯視窗:"))
