# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us17.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1201, 503)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTableWidget(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 1181, 421))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.treeView.setFont(font)
        self.treeView.setStyleSheet("QTableWidget {\n"
"    alternate-background-color: #f2f2f2; /* 隔行背景顏色 */\n"
"    selection-background-color: #0078d7;  /* 選擇背景顏色 */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表頭背景顏色 */\n"
"}")
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setColumnCount(0)
        self.treeView.setObjectName("treeView")
        self.treeView.setRowCount(0)
        self.treeView.verticalHeader().setDefaultSectionSize(24)
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setEnabled(True)
        self.cancel.setGeometry(QtCore.QRect(420, 440, 171, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancel.setObjectName("cancel")
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        self.upload.setEnabled(True)
        self.upload.setGeometry(QtCore.QRect(610, 440, 181, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.upload.setFont(font)
        self.upload.setFocusPolicy(QtCore.Qt.NoFocus)
        self.upload.setObjectName("upload")
        self.clean = QtWidgets.QPushButton(self.centralwidget)
        self.clean.setEnabled(True)
        self.clean.setGeometry(QtCore.QRect(10, 440, 101, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.clean.setFont(font)
        self.clean.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clean.setObjectName("clean")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel.setToolTip(_translate("MainWindow", "檢視完整樹狀資料"))
        self.cancel.setText(_translate("MainWindow", "取消"))
        self.upload.setToolTip(_translate("MainWindow", "上傳預覽版"))
        self.upload.setText(_translate("MainWindow", "上傳"))
        self.clean.setToolTip(_translate("MainWindow", "檢視完整樹狀資料"))
        self.clean.setText(_translate("MainWindow", "清除"))
