# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us23.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editor_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.editor_input.setGeometry(QtCore.QRect(3, 120, 361, 291))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.editor_input.setFont(font)
        self.editor_input.setObjectName("editor_input")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(380, 129, 571, 281))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.tab_widget.setFont(font)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.preview_window = QtWidgets.QTextBrowser(self.tab)
        self.preview_window.setGeometry(QtCore.QRect(10, 10, 531, 231))
        self.preview_window.setObjectName("preview_window")
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.html_code_view = QtWidgets.QPlainTextEdit(self.tab_2)
        self.html_code_view.setGeometry(QtCore.QRect(20, 10, 531, 231))
        self.html_code_view.setObjectName("html_code_view")
        self.tab_widget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("MainWindow", "預覽"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("MainWindow", "html"))
