# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_us23.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editor_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.editor_input.setGeometry(QtCore.QRect(3, 120, 361, 291))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monaco,Courier New,monospace")
        font.setPointSize(12)
        self.editor_input.setFont(font)
        self.editor_input.setStyleSheet("QPlainTextEdit {\n"
"    /* 強制白色背景 */\n"
"    background-color: #ffffff;\n"
"    \n"
"    /* 加上明確的邊框，或是 border: none，這會打破系統原生樣式 */\n"
"    border: 1px solid #e1e1e1; \n"
"    \n"
"    color: #000000;\n"
"    padding: 8px;\n"
"    font-family: \"Consolas\", \"Monaco\", \"Courier New\", monospace;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"/* 確保在一般、聚焦、甚至停用狀態下的顏色都受控 */\n"
"QPlainTextEdit:enabled {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    background-color: #ffffff; /* 如果你不想要灰灰的，這裡也要改回白色 */\n"
"    border: 1px solid #0078D7; /* 聚焦時藍色邊框，這很有專業感 */\n"
"}")
        self.editor_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editor_input.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.editor_input.setObjectName("editor_input")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(380, 129, 571, 281))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.tab_widget.setFont(font)
        self.tab_widget.setStyleSheet("/* 1. 設定分頁主體面板 (與下方 Tab 接合處) */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #C4C4C3;\n"
"    background-color: white;\n"
"    /* 這裡如果是 Tab 在下方，面板的底邊框可以保留或微調 */\n"
"}\n"
"\n"
"/* 2. 設定標籤列基礎樣式 */\n"
"QTabBar::tab {\n"
"    background: #f0f0f0;\n"
"    border: 1px solid #C4C4C3;\n"
"    border-top: none;             /* 關鍵：移除上邊框，讓它與上方內容接合 */\n"
"    \n"
"    /* 圓角設定在下方 */\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    \n"
"    /* 寬度控制 */\n"
"    min-width: 120px;            /* 設定最小寬度，不會縮成一團 */\n"
"    padding: 8px 20px;           /* 左右內距讓標籤隨文字自動撐開 */\n"
"    \n"
"    margin-right: 4px;\n"
"    color: #555;\n"
"}\n"
"\n"
"/* 3. 當 Tab 被選中時 (Active) */\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    color: #0078D7;              /* 選中時的文字顏色 */\n"
"    font-weight: bold;\n"
"    border-top: 2px solid #0078D7; /* 在接合處增加一條線，增加設計感 */\n"
"    margin-top: -1px;            /* 往上移動 1px 覆蓋面板邊框 */\n"
"}\n"
"\n"
"/* 4. 滑鼠懸停樣式 */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: #e5e5e5;\n"
"}")
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.html_code_view = QtWidgets.QPlainTextEdit(self.tab_2)
        self.html_code_view.setGeometry(QtCore.QRect(20, 10, 491, 201))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monaco,Courier New,monospace")
        font.setPointSize(12)
        self.html_code_view.setFont(font)
        self.html_code_view.setStyleSheet("QPlainTextEdit {\n"
"    /* 背景顏色：深灰色或淺灰色，這裡選用輕量感的淺灰 */\n"
"    background-color: #f8f9fa;\n"
"    \n"
"    /* 文字顏色 */\n"
"    color: #24292e;\n"
"    \n"
"    /* 邊距：讓程式碼不要貼邊 (上 右 下 左) */\n"
"    padding: 15px;\n"
"    \n"
"    /* 移除邊框（因為 tab_widget 已經有框了） */\n"
"    border: none;\n"
"    \n"
"    /* 寫程式專用字體：優先順序為 Consolas -> Monaco -> 等寬字型 */\n"
"    font-family: \"Consolas\", \"Monaco\", \"Courier New\", monospace;\n"
"    \n"
"    /* 字體大小 12pt */\n"
"    font-size: 12pt;\n"
"    \n"
"}\n"
"\n"
"/* 選取文字時的顏色 */\n"
"QPlainTextEdit:focus {\n"
"    background-color: #f0f1f2;\n"
"}")
        self.html_code_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.html_code_view.setFrameShadow(QtWidgets.QFrame.Plain)
        self.html_code_view.setReadOnly(True)
        self.html_code_view.setObjectName("html_code_view")
        self.tab_widget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.style_code_view = QtWidgets.QPlainTextEdit(self.tab_3)
        self.style_code_view.setGeometry(QtCore.QRect(50, 80, 461, 71))
        self.style_code_view.setStyleSheet("QPlainTextEdit {\n"
"    /* 背景顏色：深灰色或淺灰色，這裡選用輕量感的淺灰 */\n"
"    background-color: #f8f9fa;\n"
"    \n"
"    /* 文字顏色 */\n"
"    color: #24292e;\n"
"    \n"
"    /* 邊距：讓程式碼不要貼邊 (上 右 下 左) */\n"
"    padding: 15px;\n"
"    \n"
"    /* 移除邊框（因為 tab_widget 已經有框了） */\n"
"    border: none;\n"
"    \n"
"    /* 寫程式專用字體：優先順序為 Consolas -> Monaco -> 等寬字型 */\n"
"    font-family: \"Consolas\", \"Monaco\", \"Courier New\", monospace;\n"
"    \n"
"    /* 字體大小 12pt */\n"
"    font-size: 12pt;\n"
"    \n"
"}\n"
"\n"
"/* 選取文字時的顏色 */\n"
"QPlainTextEdit:focus {\n"
"    background-color: #f0f1f2;\n"
"}")
        self.style_code_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.style_code_view.setFrameShadow(QtWidgets.QFrame.Plain)
        self.style_code_view.setReadOnly(True)
        self.style_code_view.setObjectName("style_code_view")
        self.tab_widget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("MainWindow", "預覽"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Html"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3), _translate("MainWindow", "Style"))
